sudo: true

language: java

services:
  - docker

jdk:
  - openjdk11

script:
  - docker network create nldiCrawler
  - docker run --rm -v /var/run/docker.sock:/var/run/docker.sock -v "$TRAVIS_BUILD_DIR":/usr/src/mymaven -w /usr/src/mymaven --network=nldiCrawler -e TESTING_DATABASE_PORT=5432 -e TESTING_DATABASE_ADDRESS=nldiDatabase -e TESTING_DATABASE_NETWORK=nldiCrawler maven:3.6.0-jdk-11 mvn clean verify
  - docker network rm nldiCrawler


after_success:
  - bash <(curl -s https://codecov.io/bash)
